name: eth_url_parser
description: Module that supports parsing / parsing of all the different
  ethereum standard urls
version: 0.0.6
repository: https://github.com/fuseio/eth_url_parser
homepage: https://fuse.io

environment:
  sdk: '>=2.18.5 <4.0.0'

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.6
  freezed: ^2.3.5
  json_serializable: ^6.7.1
  lints: ^2.1.1
  test: ^1.24.4
