name: eth_url_parser
description: Module that supports parsing / parsing of all the different
  ethereum standard urls
version: 0.0.7
repository: https://github.com/fuseio/eth_url_parser
homepage: https://fuse.io

environment:
  sdk: ">=3.2.0 <4.0.0"

dependencies:
  freezed_annotation: ^2.4.1
  json_annotation: ^4.8.1

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.6
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.2
