name: eth_url_parser
description: Module that supports parsing / parsing of all the different
  ethereum standard urls
version: 0.0.4
repository: https://github.com/fuseio/eth_url_parser
homepage: https://chargeweb3.com/

environment:
  sdk: ">=2.18.5 <3.0.0"

dependencies:
  freezed_annotation: ^2.2.0
  json_annotation: ^4.8.0

dev_dependencies:
  build_runner: ^2.3.3
  freezed: ^2.3.2
  json_serializable: ^6.6.0
  lints: ^2.0.0
  test: ^1.22.2
